[package]
name = "megit_plot"
version = "0.1.0"
edition = { workspace = true }
rust-version = { workspace = true }
readme = { workspace = true }
license = { workspace = true }


[dependencies]
plotters = "0.3.4"
