[package]
name = "megit_cli"
version = "0.1.0"
edition = { workspace = true }
rust-version = { workspace = true }
readme = "../../README.md"
license = "MIT"


[dependencies]
clap = { version = "4.3.0", features = ["derive"] }



[[bin]]
name = "megit"
