[package]
name = "megit_git"
version = "0.1.0"
edition = { workspace = true }
rust-version = { workspace = true }
readme = { workspace = true }
license = { workspace = true }

[dependencies]
git2 = { version = "0.17.1", features = ["vendored-libgit2"] }
